#!/bin/bash

# function to get DNS records for a subdomain
function get_dns_records {
    domain=$1
    subdomain=$2
    dns_records=$(dig $subdomain.$domain +short)
    if [ -z "$dns_records" ]
    then
        echo "No DNS records found for subdomain $subdomain"
    else
        for record in $dns_records
        do
            echo "The subdomain $subdomain is a $(echo $record | awk '{print toupper($1)}') record and points to $record"
        done
    fi
}

# check if domain and subdomain arguments were passed
if [ $# -eq 0 ]
then
    echo "Please provide a domain to audit"
    exit 1
elif [ $# -eq 1 ]
then
    # display information for default subdomains
    domain=$1
    get_dns_records $domain "www"
    get_dns_records $domain "lb-01"
    get_dns_records $domain "web-01"
    get_dns_records $domain "web-02"
else
    # display information for specified subdomain
    domain=$1
    subdomain=$2
    get_dns_records $domain $subdomain
fi

